### ISSUE TITLE
Magnet link not working

### ISSUE THREAD

**Issue by TheRubiksGamer** [dsiguide/dsiguide.github.io#15]
In the downgrade - easy method, the magnet link for dsikey.bin doesn't seem to be hyperlinked correctly.

**Comment by lukehasawii** [comment]
Working to fix, stay posted

**Comment by TheRubiksGamer** [comment]
Thanks!

**Comment by lukehasawii** [comment]
Fixed magnet link on https://dsiguide.me/downgrading
https://dsiguide.me/downgrading-easy does not need the magnet link anymore.
