### ISSUE TITLE
It seems 256 MB SD card doesn’t work

### ISSUE THREAD

**Issue by Ronbo4512** [dsiguide/dsiguide.github.io#17]
I tried to follow the guide but I kept getting a white screen when trying to downgrade from 1.4.5u using TWLnf. I tried reformatting the SD card and disabling ‘Start to Calendar’, and still am stuck at a white screen. I got a 4 GB SD card and I downgraded!

**Comment by lukehasawii** [comment]
Head to https://www.discord.gg/w4SKAr8 if your issue persists.
