### ISSUE TITLE
Downgrade 1.4.3E

### ISSUE THREAD

**Issue by wb9688** [dsiguide/dsiguide.github.io#19]
https://dsiguide.me/downgrading-easy says that'll only work on U versions. However I've 1.4.3E, so I looked further and saw that https://dsiguide.me/downgrading doesn't mention anything about U. Is it correct that it'll work on 1.4.3E? How high are the chances on a brick when you just follow those instructions? Can those bricks be fixed? And is there no easy way for E? Thanks! Btw the Discord links are expired.

Edit: I read somewhere else that ugopwn (which is used in both tutorials) only works on U, so is there nothing I can do to downgrade? And why does the advanced tutorial not have that warning?

**Comment by lukehasawii** [comment]
Will correct changes soon. E reigon release will be out eventually.

**Comment by chronoss09** [comment]
The last ugopwn version haven't EUR file, it's not available yet?

**Comment by Robz8** [comment]
Nope, it's not released yet.
